### ISSUE TITLE
What is elasticsearch? How to get anything to work?

### ISSUE THREAD

**Issue by dashxdr** [AlphaReign/scraper#16]
Pretend I'm an idiot. How do I actually use this thing?

Does scraper spawn elasticsearch? Does elasticsearch have to be spawned somewhere else? When you say "install elasticsearch" are we talking about "npm install elasticsearch" or do I do it at the OS level? If npm, do I install it globally?

Ok so we configure 127.0.0.1:9200, do I point my browser to that address? I get connection refused.

WTF is elasticsearch and how does it fit in with scraper?

**Comment by Raxvis** [comment]
ElasticSearch is a piece of software that you will have to install.  https://www.elastic.co/products/elasticsearch

The scraper uses it to store the data and then search from it

**Comment by dashxdr** [comment]
Does installing elasticsearch do it? Or is there some configuration for it. Is it running in the background all the time on my OS even if I want to just test out your scraper program? Is it a commercial product? Do I have to pay for it?

I'm running ubuntu. There is no package for elasticsearch for ubuntu. Is elasticsearch as described in the URL you provided different from the NPM elasticsearch module? Does THAT need to be installed also?

Do you see where I'm going with all this? It may be completely obvious to you how to get your program working. But anyone new coming to it will likely abandon the effort part way. You probably think I'm an asshole. Most people won't give you feedback. At least I'm trying to help you make your open source project more useful. I know how to develop software, and even I struggled to get your s***t working. And I gave up and created the issue here. Which you dutifully closed without really offering much help at all...

Thanks!

**Comment by Raxvis** [comment]
This is a project I no longer support or actively developing.

Also, if you read the link I sent you too, it will give you answers to at least half the questions you have, but you are too lazy to go and read any of it.

1. Installing elasticsearch should get you past the 'install elasticsearch' step.
2. If it's on the same machine, no configuration.  If it's on a different machine, update the ip from 127.0.0.1 to whatever the other machine is. This doesn't even matter since you are just testing this out.
3. It's a service, like mysql, php, node, etc etc... It's running until you tell it to stop.
4. Yes, it's what I would consider commercial (pay for support / hosting if not doing it yourself)
5. No, the software is free.  You pay for support
6. Installation here: https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html. Literally google 'apt-get install elasticsearch' and there you go.  Lazy.
7. NPM is for node, the url I sent you has nothing to do with that... Seriously, read something on the page
8. The NPM ElasticSearch module is in the package.json so it will install when you install the scraper


Now, that I have said that, this project is not for you.  You have no understanding of npm or even a concept of one of the core pieces of technology this project uses.  You will be fighting things that you don't even understand.  On top of that, you clearly get pissed when you don't get spoon fed which I won't do for you.

**Comment by dashxdr** [comment]
One issue was I misread elasticsearch as elastisearch (like Elasti-Girl). So ubuntu has an elasticsearch package and I installed it.

Now here are some other required steps that weren't obvious. pm2? Like you pretend people are expert on that also. Your pm2 launch fails. But where are the logs? OK so now we have to become expert at pm2. "pm2 log 0". Fine. Now we get error messages. And so we know there are missing npm modules

npm install lodash
npm install elasticsearch
npm install bittorrent-tracker
npm install bencode
npm install bitfield

Now it runs but evidently there is some additional configuration needed.

0|index    | UDP Server listening on 0.0.0.0:6881
0|index    | Elasticsearch ERROR: 2018-04-03T19:21:48Z
0|index    |   Error: Request error, retrying
0|index    |   POST http://127.0.0.1:9200/torrents/hash/_search?size=75 => connect ECONNREFUSED 127.0.0.1:9200
0|index    |       at Log.error (/ram/scraper/node_modules/elasticsearch/src/lib/log.js:225:56)
0|index    |       at checkRespForFailure (/ram/scraper/node_modules/elasticsearch/src/lib/transport.js:240:18)
0|index    |       at HttpConnector.<anonymous> (/ram/scraper/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
0|index    |       at ClientRequest.wrapper (/ram/scraper/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
0|index    |       at emitOne (events.js:77:13)
0|index    |       at ClientRequest.emit (events.js:169:7)
0|index    |       at Socket.socketErrorListener (_http_client.js:269:9)
0|index    |       at emitOne (events.js:77:13)
0|index    |       at Socket.emit (events.js:169:7)
0|index    |       at emitErrorNT (net.js:1269:8)
0|index    | Elasticsearch WARNING: 2018-04-03T19:21:48Z
0|index    |   Unable to revive connection: http://127.0.0.1:9200/
0|index    | Elasticsearch WARNING: 2018-04-03T19:21:48Z
0|index    |   No living connections
0|index    | Elasticsearch WARNING: 2018-04-03T19:21:53Z
0|index    |   Unable to revive connection: http://127.0.0.1:9200/
0|index    | Elasticsearch WARNING: 2018-04-03T19:21:53Z
0|index    |   No living connections
0|index    | Elasticsearch WARNING: 2018-04-03T19:21:58Z
0|index    |   Unable to revive connection: http://127.0.0.1:9200/

**Comment by Raxvis** [comment]
> OK so now we have to become expert at pm2

Are you kidding me?  pm2 is incredibly well documented.  Why are you bitching about something so simple and easy to do.  It's literally, Google pm2 -> click on page about pm2 -> wow, all the answers are right there... it's like, the hardest work every done, to actually have to read something, or understand something.

>npm install lodash
npm install elasticsearch
npm install bittorrent-tracker
npm install bencode
npm install bitfield

Um, do you even understand how node projects work?  Those would have been installed if you literally ran npm install which is the first thing someone does with a node project if you know anything about node projects.

Did you install ElasticSearch?  then start it?  It is a program.

**Comment by dashxdr** [comment]
"Did you install ElasticSearch? then start it? It is a program."
Yes and by default it does nothing. It's not listening on port 9200. You seem to assume everything will just work. Your README file is worse than useless. Deal with it. Don't pretend your shit doesn't stink.

**Comment by Raxvis** [comment]
By default it does nothing?  Literally, installing and starting elasticsearch puts it running on port 9200 on 127.0.0.1 

Of course the readme sucks.  I don't maintain this. I am not currently working on this.  I don't support this.  This is not a project I am trying make into something.  It was open sourced so other people (who could develop) could take it and make it into something.
